version: "3.8"

services:
  glpi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glpi_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./storage/glpi:/var/www/html/glpi
      - ./storage/plugins:/var/lib/glpi/plugins
    ports:
      - "8080:80"
